### ISSUE TITLE
text stream is too long

### ISSUE THREAD

**Issue by jmokoistinen** [eddieantonio/isri-ocr-evaluation-tools#10]
I tried to run accuracy command with documents containing more than 20000 words. Is there any solution for large documents? 

Just a novice in C coding, I tried to modify sync.c file without success. 
If MAX_F size is increased that causes core segmentation fault (at the function fastukk_sync)

**Comment by eddieantonio** [comment]
Interesting! I'll have to investigate, though I won't have time until Saturday. In the meantime, is it okay if you use split the documents into smaller chunks that the tools can manage?

Also, what platform are you on? OS X, Linux?

**Comment by jmokoistinen** [comment]
Great thanks, Linux.

**Comment by eddieantonio** [comment]
@jmokoistinen The reason bumping `MAX_F` caused issues is because the type that's used to store character offsets, (simply called `F` in `sync.c`) was 16-bits big, and could only represent up to 65,535 characters. I changed the integer type to `ufast32_t` which should be *at least* 32 bits (so ~4 billion characters). This will probably be enough!

Clone and build master; this works on Travis-CI (a Linux box), but let me know if it works for you as well.

**Comment by jmokoistinen** [comment]
Yes it works fine now! Thanks for quick fix!
